apiVersion: v1
kind: Namespace
metadata:
    name: registry

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  ports:
    - port: 5000
  selector:
    app: registry

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: registry
  annotations:
    "kubernetes.io/ingress.class": ambassador
spec:
  tls:
  - hosts:
      - registry.easeof.com
    secretName: cert--registry-easeof-com
  rules:
    - host: registry.easeof.com
      http:
        paths:
        - backend:
            serviceName: registry
            servicePort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry
        ports:
        - containerPort: 5000
