#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

"$dir/script/update" "$@"

docker run \
  --rm  \
  -ti \
  -v "$dir/services/poddle-web/js:/opt/lorcan" \
  -w /opt/lorcan \
  -p 3000:3000 \
  node \
    npm run dev
